import Navbar from "@/components/common/landing-page/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Get Franchise",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
