import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";



const inter = Inter({
    variable: "--font-inter",
    weight:["100","200","300","400","500","600"],
})

export const metadata: Metadata = {
  title: "Get Franchise - Get Your Desired Franchise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
