import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/tanstack-provider";
import { Toaster } from "@/components/ui/sonner";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Get Franchise - Get Your Desired Franchise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} antialiased`}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
